# baseURL 변경
baseURL = ""
languageCode = "ko-KR"
defaultContentLanguage = "ko"

# title 변경
title = "AWS IoT Secure Tunnel 구성"
theme = "hugo-theme-learn"
themesdir = "."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
#ignoreFiles = [ "\\.*lab3\\.*" ]

# description, author 변경
[params]
  description = "AWS IoT Secure Tunnel 구성"
  author = "Yijeong Cho"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages.ko]
title = "AWS IoT Secure Tunnel 구성"
weight = 1
languageName = "한국어"

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> 크레딧"
url = "/credits/"
weight = 30